# Use the official Redis image as the base image
FROM redis:latest

# (Optional) Expose Redis port
EXPOSE 6380

# Default command (not necessary to specify since it's in the base image)
CMD ["redis-server"]
